spring.application.name=JPADemo-2
# PostgreSQL connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/Spring
#spring.datasource.username=postgres
#spring.datasource.password=Tiger
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d8mp1mho3t8c73c3ahr0-a:5432/jpademo_2
spring.datasource.username=jpademo_2_user
spring.datasource.password=dVhVWWitHDxNXB5k7ER1WPW6xrEe6qn9


# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
